package mrg8

import chisel3._

/**
  * This provides an alternate way to run tests, by executing then as a main
  * From sbt (Note: the test: prefix is because this main is under the test package hierarchy):
  * {{{
  * test:runMain mrg8.Mrg8Main
  * }}}
  * To see all command line options use:
  * {{{
  * test:runMain mrg8.Mrg8Main --help
  * }}}
  * To run with verilator:
  * {{{
  * test:runMain mrg8.Mrg8Main --backend-name verilator
  * }}}
  * To run with verilator from your terminal shell use:
  * {{{
  * sbt 'test:runMain mrg8.Mrg8Main --backend-name verilator'
  * }}}
  */
object Mrg8Main extends App {
  iotesters.Driver.execute(args, () => new Mrg8) {
    c => new Mrg8UnitTester(c)
  }
}

/**
  * This provides a way to run the firrtl-interpreter REPL (or shell)
  * on the lowered firrtl generated by your circuit. You will be placed
  * in an interactive shell. This can be very helpful as a debugging
  * technique. Type help to see a list of commands.
  *
  * To run from sbt
  * {{{
  * test:runMain mrg8.Mrg8Repl
  * }}}
  * To run from sbt and see the half a zillion options try
  * {{{
  * test:runMain mrg8.Mrg8Repl --help
  * }}}
  */
object Mrg8Repl extends App {
  iotesters.Driver.executeFirrtlRepl(args, () => new Mrg8)
}
